// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhGd9qqOcZ6MpjXqBbxaYDkINGpXepxfQ',
    appId: '1:38263348990:web:6e41dd32d4eebf31910faf',
    messagingSenderId: '38263348990',
    projectId: 'dispmoviles-94cb6',
    authDomain: 'dispmoviles-94cb6.firebaseapp.com',
    storageBucket: 'dispmoviles-94cb6.appspot.com',
    measurementId: 'G-4KE1FSPG8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1QokETmwcXapk94LqZt3DA7fWDCekVv8',
    appId: '1:38263348990:android:3120f5bec6dfac1e910faf',
    messagingSenderId: '38263348990',
    projectId: 'dispmoviles-94cb6',
    storageBucket: 'dispmoviles-94cb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCah_VIncqb2craQtXAsSCLRIRpR7YsqK4',
    appId: '1:38263348990:ios:31e6438018b57c29910faf',
    messagingSenderId: '38263348990',
    projectId: 'dispmoviles-94cb6',
    storageBucket: 'dispmoviles-94cb6.appspot.com',
    iosBundleId: 'com.example.movilesExamen2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCah_VIncqb2craQtXAsSCLRIRpR7YsqK4',
    appId: '1:38263348990:ios:31e6438018b57c29910faf',
    messagingSenderId: '38263348990',
    projectId: 'dispmoviles-94cb6',
    storageBucket: 'dispmoviles-94cb6.appspot.com',
    iosBundleId: 'com.example.movilesExamen2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhGd9qqOcZ6MpjXqBbxaYDkINGpXepxfQ',
    appId: '1:38263348990:web:e9454b5e3530e5a0910faf',
    messagingSenderId: '38263348990',
    projectId: 'dispmoviles-94cb6',
    authDomain: 'dispmoviles-94cb6.firebaseapp.com',
    storageBucket: 'dispmoviles-94cb6.appspot.com',
    measurementId: 'G-NMGRZJQQWX',
  );
}
